- hosts: all
  become: yes
  tasks: 
  - name: Run tasks with loop
    ansible.builtin.include_role:
      name: "{{ item }}"
    loop:
      - apache
      - packages
      - wordpress
      - db
    loop_control:
      loop_var: item
      