- name: Download wordpress
  get_url:
    url: "{{ url }}"
    dest: "{{ tar_gz_file }}"

- name: Extract file
  unarchive:
    src: "{{ tar_gz_file }}"
    dest: "{{ remote_tar_file }}"
    remote_src: yes

- name: Copy file with owner and permissions
  copy:
    src: "{{ tar_gz_file1 }}"
    dest: "{{ tar_file }}"
    owner: apache
    group: apache
    mode: '0755'
    remote_src: yes

- name: Template a file to html folder
  ansible.builtin.template:
    src: "{{ templ_php_from }}"
    dest: "{{ templ_php_to }}"

- name: Restart Apache
  service:
    name: "{{ apache }}"
    state: restarted
